# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dAfYVZ6sH9SN94XPqFPPd4IVE4K8-QsJ
"""

file1="history is the systematic study of the past"
file2=" History is the systematic of the past this is just for practice "
def jaccard_similarity (file1,file2):
   #split texts into sets of words
   set1=set(file1.split())
   set2=set(file2.split())

   #find the intersection and union
   intersection = set1.intersection(set2)
   union= set1.union(set2)

   #calculate jaccard similarity
   similarity = len(intersection) / len(union)

   #return similarity and intersecting words
   return similarity , intersection

#Call the function here:
similarity, common_words = jaccard_similarity(file1, file2)


# Print the outcomes
print(f"Similarity: {similarity:.2f}")
print(f"Common words: {common_words}")